<?php
namespace frontend\widgets\sitesearch;

use yii\bootstrap\Widget;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use frontend\widgets\sitesearch\SearchForm;

/**
 * User: Администратор
 * Date: 03.04.2017
 * Time: 21:17
 */
class SiteSearch extends Widget
{
    public $model;
    public $form;

    public function init()
    {
        parent::init();
        ob_start();

    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub


        $this->model = new SearchForm();

        $this->form = ActiveForm::begin( [ 'id'      => 'searchFrm',
                                           'options' => [ 'class' => 'form-inline' ] ] );

//        $this->form->field( $this->model, 'qact' )->hiddenInput( [ 'options' => [
//            'value' => 'search_adv' ] ] );

//    <input type="hidden" name="qact" value="search_adv">
//    <input type="hidden" name="SortBy" value="Time">
//    <input type="hidden" name="Dir" value="d">
//    <input type="hidden" name="City" value="-1">
//    <input type="hidden" name="Folder" value="-1">
//    <input type="hidden" name="Type" value="-1">
//    <input type="hidden" name="Price_Start" value="">
//    <input type="hidden" name="Price_End" value="">
//    <input type="hidden" name="Currency" value="1">
//    <input type="hidden" name="Period" value="3000">
//    <input type="hidden" name="OwnerAdvID" value="0">

        //var_dump($this->form);
//        $this->form->field( $this->model, 'searchWord' )->textInput( [ 'autofocus'   => true,
//                                                                       'placeholder' => 'Поиск объявления' ] )->label( '' );
//
        Html::submitButton( 'Submit', [ 'class' => 'btn btn-primary',
                                        'style' => 'margin-bottom: 10px;' ] );

        ActiveForm::end();


        $this->form = ob_get_clean();
        return $this->form;

    }
}

?>