<?php

use yii\bootstrap\Widget;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/**
 * User: Администратор
 * Date: 03.04.2017
 * Time: 21:17
 */
class SiteSearch extends Widget
{
//    public function init()
//    {
//        $form = ActiveForm::begin( [ 'id' => 'form-site-search' ],
//            'options' => ['class' => 'form-horizontal']
//    );
//        $form->field( $model, 'search-word' )->textInput( [ 'autofocus' => true ] );
//    }
//
//    public function run()
//    {
//        parent::run(); // TODO: Change the autogenerated stub
//    }
}